# -*- coding: utf-8 -*-
"""Data_Cleaning_&_Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a1WRL265o7dHHx6UIGwECC5ath60Mfyz
"""

# importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder

#Import the dataset and explore basic info (nulls, data types)
df = pd.read_csv('Titanic-Dataset.csv')
print(df.info())
print(df.head())
print(df.isnull().sum())

#Handle missing values using mean/median/imputation.
df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
df.drop(columns=['Cabin'], inplace=True)

#Convert categorical features into numerical using encoding.

le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])         # male=1, female=0
df['Embarked'] = le.fit_transform(df['Embarked'])  # S=2, C=0, Q=1

#Normalize/standardize the numerical features.

scaler = StandardScaler()
num_cols = ['Age', 'Fare', 'SibSp', 'Parch']
df[num_cols] = scaler.fit_transform(df[num_cols])

# Visualize outliers using boxplots and remove them.
# Boxplots
for col in num_cols:
    sns.boxplot(data=df[col])
    plt.title(f'Boxplot of {col}')
    plt.show()

# Remove outliers using IQR
for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    df = df[(df[col] >= Q1 - 1.5 * IQR) & (df[col] <= Q3 + 1.5 * IQR)]

df.to_csv('Titanic-Cleaned.csv', index=False)